// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPBCekuTkIa2gH7Vqv0HREWlN52nHNPE',
    appId: '1:394616728305:web:d97c2e86038622313cd750',
    messagingSenderId: '394616728305',
    projectId: 'pushnotific-2d30e',
    authDomain: 'pushnotific-2d30e.firebaseapp.com',
    storageBucket: 'pushnotific-2d30e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkTQ3WmkCyfSvezs9BIeC_wRDCED9hr9E',
    appId: '1:394616728305:android:24ae60ede144524c3cd750',
    messagingSenderId: '394616728305',
    projectId: 'pushnotific-2d30e',
    storageBucket: 'pushnotific-2d30e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbPBCekuTkIa2gH7Vqv0HREWlN52nHNPE',
    appId: '1:394616728305:web:5b499ee97d745eca3cd750',
    messagingSenderId: '394616728305',
    projectId: 'pushnotific-2d30e',
    authDomain: 'pushnotific-2d30e.firebaseapp.com',
    storageBucket: 'pushnotific-2d30e.appspot.com',
  );
}
